config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'emails', to: 'omniauth_callbacks#request_email'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  resources :subscriptions
  resources :attaches
  resources :searches do
    post :search_hound, on: :collection
  end

  resources :authorizations do
    get :confirm_email, on: :member
  end

  resources :questions do
    resources :votes, shallow: true
    resources :comments
    resources :answers, shallow: true do
      patch :assign_best, on: :member
      resources :comments
      resources :votes, shallow: true
    end
  end

  root 'questions#index'
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/question.rb
class Question < ApplicationRecord
  include VotesActions

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :attaches, as: :attachable, dependent: :destroy
  has_many :votes, as: :subject, dependent: :destroy
  has_many :comments, as: :commented, dependent: :destroy

  scope :created_yesterday, -> { where(created_at: (Time.current.localtime.yesterday.beginning_of_day..Time.current.localtime.yesterday.end_of_day)) }

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attaches, reject_if: proc { |attrib| attrib['file'].nil? }
  after_create_commit :publish_question
  after_update_commit :update_question
  after_destroy_commit :destroy_question

  private

  def publish_question
    return if errors.any?
    CreateQuestionJob.perform_later(user, self)
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        json: { publish: { question: self, author: user } }
      )
    )
  end

  def update_question
    return if errors.any?
    ["questions/#{id}/question_update", "questions"].each do |stream|
      ActionCable.server.broadcast(
      stream,
      ApplicationController.render(
        json: { update: { question: self } }
        )
      )
    end
  end

  def destroy_question
    return if errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        json: { destroy: { question: self } }
      )
    )
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: %i[show edit update destroy]

  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    respond_with @question, serializer: QuestionWithoutAnswersSerializer, root: 'question'
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with @question
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :best_answer, attaches_attributes: %i[id _destroy file])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :gon_user, unless: :devise_controller?

  respond_to :html, only: %i[index show]
  respond_to :js, except: %i[index show]

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def show
    respond_with @question
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :best_answer, attaches_attributes: %i[id _destroy file])
  end

  def gon_user
    gon.author_id = current_user.id if current_user
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
-if question.persisted?
  tr.row class="question_#{question.id}"
    td.rating = "#{question.votes_count}"
    td.index_question_body
      = link_to " #{question.title}", question_path(question)
      .adv_info
        .info_line = "автор: #{current_user&.author_of?(question) ? "это Ваш вопрос" : question.user.email}, проголосовало: #{question.votes.count}, ответов: #{question.answers.count}"
        .manage.favorites = link_to 'в избранное'
        .manage.delete_question = link_to 'удалить', question_path(question), method: :delete, remote: true, data: { confirm: 'Вы уверены?' } if current_user&.author_of?(question)

app/views/questions/create.js.erb
$('.alert').remove();
<% if @question.errors.any? %>
  $(' <%= j render "common/errors", resource: @question %>').insertAfter('.new_question_form');
<% else %>
  // flashing a notice
  $('<%= j bootstrap_flash %>').insertBefore('.ask_question');
  // form is reset and hidding
  $('form#new_question')[0].reset();
  $('.new_question').off().hide();
  $('.ask_question').show();
  // fadding out
  $('.alert-success').addClass('fadeOut');
  $('.fadeOut').one("webkitAnimationEnd oanimationend msAnimationEnd animationend", function(e){
    $('.alert').remove();
  });
<% end %>

app/views/questions/destroy.js.erb
  // flashing a notice
  $('<%= j bootstrap_flash %>').insertBefore('.ask_question');
  // fadding out
  $('.alert-success').addClass('fadeOut');
  $('.fadeOut').one("webkitAnimationEnd oanimationend msAnimationEnd animationend", function(e){
    $('.alert').remove();
  });

app/views/questions/index.html.slim
.errors_explanation
- if can?(:create, Question)
  div = link_to 'Задать вопрос','', class: "ask_question"
.new_question_form
= nested_form_for @question = Question.new, remote: true do |f|
  p
    = f.label :title
    = f.text_field :title, class: 'form-control'
  p
    = f.label :body
    = f.text_area :body, class: 'form-control'
  p
    =f.link_to_add "Прикрепить файлы", :attaches, data: { target: '.attaches'}
    .attaches
    = render 'common/attaches', f: f, object_type: @question
  = f.submit 'Создать', title: "Создать вопрос", class: 'create_question btn btn-success'
  = f.submit 'Сбросить', type: 'reset', title: "Сбросить к начальному состоянию", class: 'clear_form btn btn-default margin_left_5px'
  a.btn.btn-link.cancel title="Отменить создание вопроса" Отменить

table.table.table-hover.exists_questions data-list="questions"
  tbody
    = render @questions.order('votes_count DESC')

app/views/questions/show.html.slim
.errors_explanation
div class="question question_#{@question.id}" data-id="#{@question.id}"
  h3.question_title =@question.title
  .question_vote_box
    - if can?(:vote, @question)
      .vote = link_to 'like', question_votes_path(@question, votes_value: 1 ), class: 'like', remote: true, method: :post if current_user
    .question_votes_count class="question_votes_count_#{@question.id}"  = @question.votes_count
    - if can?(:vote, @question)
      .vote =link_to 'dislike', question_votes_path(@question, votes_value: -1 ), class: 'dislike', remote: true, method: :post if current_user
  .main.question_main
    .question_body
      =@question.body
      - unless @question.attaches.count.zero?
        div Вложения:
        table
          -@question.attaches.each do |attach|
            tr.row id="file_#{attach.id}"
              td.col-md-1=link_to attach.file.identifier, attach.file.url
              - if current_user&.author_of?(@question)
                td.col-md-1.delete_attach =link_to '  delete', attach_path(attach), method: :delete, remote: true, data: { confirm: 'Вы уверены?' }
                td.col-md-10
  .advanced_staff
    .author.float_left = "Автор: #{@question.user.email}"
    - if current_user
      .manage.comment_link = link_to 'Комментировать','', class: 'new_comment_link', data: { class: ".question_#{@question.id}" }
      - if Subscription.where(user: current_user, question: @question).first
        .manage.subscribe = link_to 'Отписаться', subscription_path(@question), method: :delete, remote: true
      - else
        .manage.subscribe = link_to 'Подписаться', subscriptions_path(id: @question), method: :post, remote: true
    - if current_user&.author_of?(@question)
      .manage.delete_question = link_to 'Удалить', question_path(@question), method: :delete, remote: true, data: { confirm: 'Вы уверены?' }
      .manage.edit_question =link_to 'Редактировать','', class: 'edit_question_link'
      .edit_question_form
        =form_for @question, remote: true do |f|
          p=f.label :title, 'Title'
          p=f.text_field :title
          p=f.label :body, 'Body'
          p=f.text_area :body, rows: 5
          p=f.submit 'Save'
          br
  .comments
    = render @question.comments
  = render 'common/comments_form', commented: @question

.exists_answers
  div
    =render 'answers/answers'

.answer_errors

-if user_signed_in?
  .new_answer_form
    =nested_form_for [@question, @answer = @question.answers.new], remote: true do |form|
      p = form.label :body
      p = form.text_area :body, rows: 5, class: 'new_answer_body'
      p = form.link_to_add "Прикрепить файлы", :attaches, data: { target: '.attaches'}
      .attaches
      p = render 'common/attaches', f: form, object_type: @answer
      p = form.submit 'Answer the question'

app/views/questions/update.js.erb
$('#errors_alert').remove();
<% if @question.errors.any? %>
  $(' <%= j render "common/errors", resource: @question %>').insertBefore('.edit_question_form');
<% else %>
  $('<%= j bootstrap_flash %>').insertBefore('.question');
  $('.edit_question_form').hide();
  $('.question_errors').hide();
  $('.question').show();
  $('.edit_question_link').show();
  // fadding out
  $('.alert-success').addClass('fadeOut');
  $('.fadeOut').one("webkitAnimationEnd oanimationend msAnimationEnd animationend", function(e){
    $('.alert').remove();
  });
<% end %>