config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'emails', to: 'omniauth_callbacks#request_email'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  resources :subscriptions
  resources :attaches
  resources :searches do
    post :search_hound, on: :collection
  end

  resources :authorizations do
    get :confirm_email, on: :member
  end

  resources :questions do
    resources :votes, shallow: true
    resources :comments
    resources :answers, shallow: true do
      patch :assign_best, on: :member
      resources :comments
      resources :votes, shallow: true
    end
  end

  root 'questions#index'
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include VotesActions

  belongs_to :question
  belongs_to :user
  has_many :attaches, as: :attachable, dependent: :destroy
  has_many :votes, as: :subject, dependent: :destroy
  has_many :comments, as: :commented, dependent: :destroy

  default_scope { order(id: 'ASC') }

  validates :body, presence: true

  accepts_nested_attributes_for :attaches, reject_if: proc { |attrib| attrib['file'].nil? }

  after_create_commit :publish_answer
  after_update_commit :update_answer
  after_destroy_commit :destroy_answer

  def best_answer_switch
    transaction do
      question.answers.where(best_answer: true).update_all(best_answer: false)
      update!(best_answer: true)
    end
  end

  private

  def publish_answer
    return if errors.any?
    ActionCable.server.broadcast(
      "questions/#{question.id}/answers",
      ApplicationController.render(
        partial: 'answers/new_answer',
        locals: { answer: self }
      )
    )
    NewAnswerJob.perform_later(self)
  end

  def update_answer
    return if errors.any?
    ActionCable.server.broadcast(
      "questions/#{question.id}/answers",
      ApplicationController.render(
        json: { update: { answer: self, datetime: updated_at.localtime.strftime("%d/%m/%Y, %H:%M") } }
      )
    )
  end

  def destroy_answer
    return if errors.any?
    ActionCable.server.broadcast(
      "questions/#{question.id}/answers",
      ApplicationController.render(
        partial: 'answers/delete_answer',
        locals: { answer: self }
      )
    )
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, :gon_user, only: :create
  before_action :set_answer, except: %i[create attach]

  respond_to :js

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params))
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    # @answer.destroy
    respond_with(@answer.destroy)
  end

  def assign_best
    @answer.best_answer_switch
    respond_with(@answer)
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attaches_attributes: %i[id file _destroy]).merge!(user: current_user)
  end

  def gon_user
    gon.author_id = current_user if current_user
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, except: :show
  authorize_resource

  def index
    @answers = @question.answers
    respond_with @answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer, serializer: AnswerWithAttrSerializer, root: 'answer'
  end

  def create
    @answer = @question.answers.create(answer_params.merge(user: current_resource_owner))
    respond_with @answer
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
-if answer.persisted?
  .answer class="#{answer.best_answer ? 'best' : 'usual'} answer_#{answer.id}"
    .answer_vote_box class="#{answer.best_answer ? 'img' : ''}"
      -if can?(:vote, answer)
        .vote = link_to 'like', answer_votes_path( answer, votes_value: 1 ), class: 'like', remote: true, method: :post if current_user
      div class="answer_votes_count_#{answer.id}"  = answer.votes_count
      -if can?(:vote, answer)
        .vote = link_to 'dislike', answer_votes_path( answer, votes_value: -1 ), class: 'dislike' , remote: true, method: :post if current_user
    .main.answer_main
      div id="editing_errors_#{answer.id}"
      .answer_body class="body_of_#{answer.id}" =answer.body
      .edit_form class="edit_form_#{answer.id}"
        = form_for answer, remote: true, data: { id: answer.id } do |f|
          p = f.label "body_#{answer.id}", 'Содержание'
          p = f.text_area :body, class: 'form-control', rows: 5, id: "answer_body_#{answer.id}"
          p = f.submit 'Save'
      ul
        -answer.attaches.each do |attach|
          li id="file_#{attach.id}"
            .link_to_file =link_to attach.file.identifier, attach.file.url, target: '_blank'
            - if current_user&.author_of?(answer)
              .delete_attach =link_to '  delete', attach_path(attach), method: :delete, remote: true, data: { confirm: 'Are you sure?' }
    .advanced_staff
      .author.float_left = "#{answer.user.email}"
      .manage.updated_at class="updated_for_#{answer.id}"  ="изм. #{answer.updated_at.localtime.strftime("%d/%m/%Y, %H:%M")}"
      .manage.comment_link = link_to 'Комментировать','', class: 'new_comment_link', data: { class: ".answer_#{answer.id}" }
      -if current_user&.author_of?(answer)
        .manage.delete_answer
          =link_to 'Удалить',  answer_path(answer), remote: true, data: { confirm: 'Are you sure?' }, method: :delete
        .manage.edit_answer
          =link_to 'Редактировать','', class: "edit-answer-link edit_answer_#{answer.id}", data: { answer_id: answer.id }
      - if current_user&.author_of?(answer.question)
        .manage.best_answer
          =link_to 'Выбрать лучшим', assign_best_answer_path(answer), method: :patch, remote: true,\
            class: "best-answer-link #{answer.best_answer ? 'now-best' : ''}", id: "best-answer-link-#{answer.id}"
    .comments
      = render answer.comments
    =render 'common/comments_form', commented: answer

app/views/answers/_answers.html.slim
=render @question.answers.order('votes_count DESC')

app/views/answers/assign_best.js.erb
<% if @answer.errors.any? %>
<% end %>

app/views/answers/create.js.erb
$('.alert').remove();
<% if @answer.errors.any? %>
  $('.new_answer_body')
    .stop()
    .css('background-color','#FF9999')
    .attr('placeholder','Введите текст ответа')
    .animate({backgroundColor: 'transparent'}, 3000)
<% else %>
  // clean up form text after creating answer
  $('form#new_answer')[0].reset()
  // delete all loader files and create one
  $('.remove_nested_fields').click();
  $('.add_nested_fields').click();
  $('.new_answer_body').attr('placeholder','')
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.any? %>
  $('#answer_body_<%= @answer.id %>')
    .stop().css('background-color','pink').attr('placeholder','Введите текст ответа').animate({backgroundColor: 'transparent'}, 3000);
<% else %>
  $('.edit_form_<%= @answer.id %>').hide();
  $('.body_of_<%= @answer.id %>').html('<%= @answer.body %>').show();
  $('.updated_for_<%= @answer.id %>').html('изм. <%= @answer.updated_at.localtime.strftime("%d/%m/%Y, %H:%M") %>').show();
  $('.edit_answer_<%= @answer.id %>').show();
  // clearing editing errors
  $('#errors_alert').empty().hide();
<% end %>